name: CI Builds

on: [push]

jobs:
  run:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetches all submodules
      - uses: actions/setup-java@v4
        with:
          distribution: 'graalvm' # See 'Supported distributions' for available options
          java-version: '24'
      - name: Execute context-mapper script
        working-directory: context-mapper
        run: sh script.sh
      - name: Check output directory
        run: ls -l context-mapper/output
